// Моковые данные для разработки

export const mockSignsData = [
  {
    id: 1,
    name: "Знак 'Главная дорога' на перекрестке ул. Ленина",
    latitude: 55.751244,
    longitude: 37.618423,
    descriptionGibdd: "Знак 2.1 'Главная дорога'. Установлен на перекрестке ул. Ленина и ул. Пушкина.",
    descriptionCommerce: "Знак приоритета 2.1, металлический, светоотражающая пленка тип B, состояние хорошее.",
    sourceGibdd: true,
    sourceCommerce: true,
    lastUpdateGibdd: "2024-03-15T00:00:00Z",
    lastUpdateCommerce: "2024-04-01T00:00:00Z",
    mergedStatus: "updated",
  },
  {
    id: 2,
    name: "Знак 'Уступи дорогу' на ул. Гагарина",
    latitude: 55.755814,
    longitude: 37.617635,
    descriptionGibdd: "Знак 2.4 'Уступи дорогу'. Установлен на пересечении с ул. Советской.",
    descriptionCommerce: null,
    sourceGibdd: true,
    sourceCommerce: false,
    lastUpdateGibdd: "2024-02-10T00:00:00Z",
    lastUpdateCommerce: "",
    mergedStatus: "new",
  },
  {
    id: 3,
    name: "Знак 'Пешеходный переход' возле школы №5",
    latitude: 55.753215,
    longitude: 37.622504,
    descriptionGibdd: null,
    descriptionCommerce: "Знак 5.19.1 'Пешеходный переход', двусторонний, на желтом фоне, требуется замена.",
    sourceGibdd: false,
    sourceCommerce: true,
    lastUpdateGibdd: "",
    lastUpdateCommerce: "2024-03-20T00:00:00Z",
    mergedStatus: "conflict",
  },
  {
    id: 4,
    name: "Знак 'Остановка запрещена' на пр. Мира",
    latitude: 55.761665,
    longitude: 37.632324,
    descriptionGibdd: "Знак 3.27 'Остановка запрещена'. Действует по рабочим дням.",
    descriptionCommerce: "Знак 3.27, односторонний, состояние удовлетворительное, требуется очистка.",
    sourceGibdd: true,
    sourceCommerce: true,
    lastUpdateGibdd: "2024-01-25T00:00:00Z",
    lastUpdateCommerce: "2024-04-05T00:00:00Z",
    mergedStatus: "conflict",
  },
  {
    id: 5,
    name: "Знак 'Ограничение скорости 40' на ул. Строителей",
    latitude: 55.758582,
    longitude: 37.642455,
    descriptionGibdd: "Знак 3.24 'Ограничение максимальной скорости' 40 км/ч.",
    descriptionCommerce: "Знак ограничения скорости до 40 км/ч, установлен на опоре освещения.",
    sourceGibdd: true,
    sourceCommerce: true,
    lastUpdateGibdd: "2024-03-01T00:00:00Z",
    lastUpdateCommerce: "2024-03-05T00:00:00Z",
    mergedStatus: "updated",
  },
  {
    id: 6,
    name: "Знак 'Движение без остановки запрещено' на ул. Космонавтов",
    latitude: 55.764976,
    longitude: 37.638575,
    descriptionGibdd: null,
    descriptionCommerce: "Знак 2.5 'Движение без остановки запрещено', требуется замена.",
    sourceGibdd: false,
    sourceCommerce: true,
    lastUpdateGibdd: "",
    lastUpdateCommerce: "2024-02-15T00:00:00Z",
    mergedStatus: "new",
  },
  {
    id: 7,
    name: "Знак 'Въезд запрещен' на ул. Парковой",
    latitude: 55.769768,
    longitude: 37.644772,
    descriptionGibdd: "Знак 3.1 'Въезд запрещен'. Кирпич.",
    descriptionCommerce: null,
    sourceGibdd: true,
    sourceCommerce: false,
    lastUpdateGibdd: "2023-12-10T00:00:00Z",
    lastUpdateCommerce: "",
    mergedStatus: "removed",
  },
  {
    id: 8,
    name: "Знак 'Парковка' у торгового центра",
    latitude: 55.753559,
    longitude: 37.609218,
    descriptionGibdd: "Знак 6.4 'Парковка (парковочное место)'.",
    descriptionCommerce: "Знак 6.4 'Место стоянки', с дополнительной информацией о режиме работы.",
    sourceGibdd: true,
    sourceCommerce: true,
    lastUpdateGibdd: "2024-01-15T00:00:00Z",
    lastUpdateCommerce: "2024-04-10T00:00:00Z",
    mergedStatus: "updated",
  },
  {
    id: 9,
    name: "Знак 'Обгон запрещен' на Садовом кольце",
    latitude: 55.757539,
    longitude: 37.626904,
    descriptionGibdd: "Знак 3.20 'Обгон запрещен'.",
    descriptionCommerce: "Знак 3.20, состояние хорошее.",
    sourceGibdd: true,
    sourceCommerce: true,
    lastUpdateGibdd: "2024-02-20T00:00:00Z",
    lastUpdateCommerce: "2024-02-25T00:00:00Z",
    mergedStatus: "updated",
  },
  {
    id: 10,
    name: "Знак 'Тупик' на ул. Заречной",
    latitude: 55.748215,
    longitude: 37.631294,
    descriptionGibdd: null,
    descriptionCommerce: "Знак 6.8.1 'Тупик', требуется обновление.",
    sourceGibdd: false,
    sourceCommerce: true,
    lastUpdateGibdd: "",
    lastUpdateCommerce: "2024-03-15T00:00:00Z",
    mergedStatus: "new",
  },
]
